---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-orders-secret
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_DB: "orders_db"
  POSTGRES_USER: "orders_user"
  POSTGRES_PASSWORD: "orders_pass"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-orders-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-orders
  namespace: ecommerce
  labels:
    app: postgres-orders
spec:
  serviceName: postgres-orders
  replicas: 1
  selector:
    matchLabels:
      app: postgres-orders
  template:
    metadata:
      labels:
        app: postgres-orders
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-orders-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "orders_user", "-d", "orders_db"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-orders-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-orders
  namespace: ecommerce
  labels:
    app: postgres-orders
spec:
  selector:
    app: postgres-orders
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
